language: node_js
cache:
  yarn: true
  directories:
  - node_modules
node_js:
  - 8
notifications:
  email: false
install:
  - yarn
script:
  - yarn test
after_success:
  - yarn publish
branches:
  only:
  - master