language: node_js
cache:
  yarn: true
  directories:
  - node_modules
node_js:
  - 8
notifications:
  email: false
branches:
  only:
  - master
install:
  - yarn
  - yarn global add lerna
script:
  - yarn test
deploy:
  provider: script
  script: yarn semantic-release
