language: node_js
cache:
  yarn: true
  directories:
  - node_modules
node_js:
  - 8
notifications:
  email: false
install:
  - yarn
  - yarn global add lerna
  - lerna bootstrap
script:
  - yarn test
deploy:
  provider: script
  script: "lerna publish --conventional-commits --yes"
branches:
  only:
  - master